### ISSUE TITLE
Can the library be used to compute point convolutions like Tensor Field Networks?

### ISSUE THREAD

**Issue by PeterHolderrieth** [QUVA-Lab/escnn#14]
So far, I have seen this library only being used for data on the grid (e.g. images in pixels). However, can it also be used for point clouds like [Tensor Field Networks](https://arxiv.org/abs/1802.08219) do? 

In principle, the theory should work the same way: just do point convolutions with equivariant kernels based on the basis defined here. However, I see that the GeometricTensor class only support real tensors, i.e. data that lies on a grid. Is there any thought on implementing that in the future?

**Comment by gianfrancortes** [comment]
@PeterHolderrieth I believe [this](https://quva-lab.github.io/escnn/api/escnn.nn.html#steerable-point-convolution) is what you're looking for.

**Comment by Gabri95** [comment]
Hi @PeterHolderrieth 

Thanks for this question! :)  As @gianfrancortes  suggested, this is indeed already possible!

However, the current implementation in the master branch is not really optimal, since the convolutional filters are implemented in numpy. 
If you want to efficiently work with point-cloud data, you may want to check out [this new branch](https://github.com/QUVA-Lab/escnn/tree/kernels_torch) (and the relative [docs](https://github.com/QUVA-Lab/escnn/tree/kernels_torch_docs)), where I reimplemented everything in pytorch (hence, supporting differentiable and cuda accelerated bases sampling). 
This branch also includes some refactoring of the interface inside `escnn.kernels`; since this is a lot of changes, I am waiting for some more testing before merging this branch into the master. However, this will eventually (soon) become the version 1.0 of the library.

Best,
Gabriele

**Comment by PeterHolderrieth** [comment]
Hi @Gabri95 and @gianfrancortes! Thanks a lot for your reply! That indeed answered my question. Appreciate it! And thanks for developing this great library!
