### ISSUE TITLE
Different change of basis matrix when restricting irreps

### ISSUE THREAD

**Issue by hlzl** [QUVA-Lab/escnn#31]
Hi Gabriele,

Why is the calculation of the [change of basis matrix in the dihedral group](https://github.com/QUVA-Lab/escnn/blob/0972a7e458c0de5ea78870f622d374b4c86588e0/escnn/group/groups/dihedralgroup.py#L451) for restricting a subgroup with reflection and rotations different compared to the [same restriction in the O2 group](https://github.com/QUVA-Lab/escnn/blob/0972a7e458c0de5ea78870f622d374b4c86588e0/escnn/group/groups/o2group.py#L513)?

Thank you,
Florian

**Comment by Gabri95** [comment]
hi @hlzl 

The reason is that `id[0]` is an integer representing a discrete rotation for [the dihedral group](https://github.com/QUVA-Lab/escnn/blob/0972a7e458c0de5ea78870f622d374b4c86588e0/escnn/group/groups/dihedralgroup.py#L451) while it is an angle in [0, 2pi) for [the O(2) group](https://github.com/QUVA-Lab/escnn/blob/0972a7e458c0de5ea78870f622d374b4c86588e0/escnn/group/groups/o2group.py#L513).
However, the function `utils.psi` expects an angle in [0, 2pi), so the integer must be converted into a rotation angle in the first case. You can see the meaning of the `id` tuple in [the Dihedral group](https://quva-lab.github.io/escnn/api/escnn.group.html#dihedral-group) and the [O2 group](https://quva-lab.github.io/escnn/api/escnn.group.html#escnn.group.O2) documentations under "Subgroup Structure".


However, you just made me realise that the documentation of the [`O2._restrict_irrep()`](https://github.com/QUVA-Lab/escnn/blob/0972a7e458c0de5ea78870f622d374b4c86588e0/escnn/group/groups/o2group.py#L438) method is incorrect, although it should not be rendered in the docs pages. 

Anyways, I will fix it, thanks!

Gabriele
