### ISSUE TITLE
Irreps of direct product

### ISSUE THREAD

**Issue by wzm2256** [QUVA-Lab/escnn#59]
Hi, I am testing the irreps of G $\times$ G, where G is SO3. I found that direct product leads to different frequencies. That causes some difficulties for me to pick the right irreps. I am not sure whether this is a design choice or a bug.

```
import escnn.group as g
r1 = g.so3_group(1)
r2 = g.so3_group(1)

r1.irreps()
# [SO(3)|[irrep_0]:1, SO(3)|[irrep_1]:3] # which is correct according to the definition

r12 = g.direct_product(r1, r2, name='1_order')

 r1.irreps()
# [SO(3)|[irrep_0]:1, SO(3)|[irrep_1]:3, SO(3)|[irrep_2]:5, SO(3)|[irrep_3]:7] # get more frequencies here

r12.irreps()
#[1_order|[irrep_[(0,),(0,)](0)]:1,
# 1_order|[irrep_[(0,),(1,)](0)]:3,
# 1_order|[irrep_[(0,),(2,)](0)]:5,
# 1_order|[irrep_[(0,),(3,)](0)]:7,
# 1_order|[irrep_[(1,),(0,)](0)]:3,
# 1_order|[irrep_[(1,),(1,)](0)]:9,
# 1_order|[irrep_[(1,),(2,)](0)]:15,
# 1_order|[irrep_[(1,),(3,)](0)]:21,
# 1_order|[irrep_[(2,),(0,)](0)]:5,
# 1_order|[irrep_[(2,),(1,)](0)]:15,
# 1_order|[irrep_[(2,),(2,)](0)]:25,
# 1_order|[irrep_[(2,),(3,)](0)]:35,
# 1_order|[irrep_[(3,),(0,)](0)]:7,
# 1_order|[irrep_[(3,),(1,)](0)]:21,
# 1_order|[irrep_[(3,),(2,)](0)]:35,
# 1_order|[irrep_[(3,),(3,)](0)]:49]

# I do not need frequency 2 and 3 in r12 r1 and r2

```

**Comment by Gabri95** [comment]
Hi @wzm2256 

I think the issues is that you should not assume the `Group.irreps()` dictionary to be immutable, but it always stores all irreps instantiated so far.
The effect of calling `so3_group(F)` is only that of initializing the dictionary with irreps up to frequency `F`.
Since the instance of SO3 returned by `so3_group()` is always the same, if you later call `so3_group(L)` with `L > F`, the dictionary `SO3.irreps()` will also be updated with all irreps until frequency `L`.

If you only need the irreps until a certain frequency `F`, you should instead use the `SO3.bl_irreps(F)` method.



In this particular case, the reason why the frequencies increase is that the constructor of DirectProductGroup calls the `_generator()` method of SO3 (the same method called by `so3_group()`) without specifying a maximum frequency `F`, so the default `F=3` is used and all irreps up to `F=3` are now generated.
This call without this optional parameter is on purpose since DirectProductGroup is a general class which should work with any group (the notion of maximum frequency only makes sense for a few groups) and, anyways, different values of this optional parameter still lead to the same instance of SO3 being returned.

Hope this helps!

Best,
Gabriele

**Comment by wzm2256** [comment]
I see. Thanks for the explanation!
