### ISSUE TITLE
What is the intuition behind conditioning the kernel size on the number of rotations in the example script?

### ISSUE THREAD

**Issue by mertkaraoglu** [QUVA-Lab/escnn#70]
In the example [code](https://github.com/QUVA-Lab/escnn/blob/master/examples/e2wrn.py#L135), there is a condition on the number of rotations for selecting the kernel size. What is the full intuition behind it? Would using a 3 x 3 kernel for all convolutions in an SE2 equivariant CNN with 8 rotation groups be suboptimal? What can be the rule of thumb to follow for squeezing out the maximum efficiency and accuracy?

**Comment by Gabri95** [comment]
Hi @mertkaraoglu 

The idea is that only perfect equivariance to N=4 rotations can be achieved with a discrete KxK filters.
Equivariance to N>4 rotations will always be approximate. 
The intuition is that using a wider filter (K>3) allows for less discretisation artefacts and can improve stability to smaller rotations.
I don't feel like suggesting a precise rule unfortunately, since this depends a lot on your data and task.

In my experience, K=3 is often sufficient to get good performance but k=5 can still have some benefits and, in particular, can improve the overall stability of the model (maybe reducing a bit overfitting).

Hope this helps,
Gabriele

**Comment by mertkaraoglu** [comment]
> Hi @mertkaraoglu
> 
> The idea is that only perfect equivariance to N=4 rotations can be achieved with a discrete KxK filters. Equivariance to N>4 rotations will always be approximate. The intuition is that using a wider filter (K>3) allows for less discretisation artefacts and can improve stability to smaller rotations. I don't feel like suggesting a precise rule unfortunately, since this depends a lot on your data and task.
> 
> In my experience, K=3 is often sufficient to get good performance but k=5 can still have some benefits and, in particular, can improve the overall stability of the model (maybe reducing a bit overfitting).
> 
> Hope this helps, Gabriele

Thank you for the detailed reply, much appreciated.
