### ISSUE TITLE
Gimbal lock warning

### ISSUE THREAD

**Issue by pimdh** [QUVA-Lab/escnn#9]
The following code gives a Gimbal lock warning. I suppose I can ignore?
```
G = so3_group()
rho = G.irrep(1)
subgroup_id = (False, -1)
G.restrict_representation(subgroup_id, rho)
```
Gives
```
/usr2/pim/.local/lib/python3.8/site-packages/escnn/group/groups/so3_utils.py:96: UserWarning: Gimbal lock detected. Setting third angle to zero since it is not possible to uniquely determine all angles.
  return element.as_euler(param)
Out[72]: SO(2)|[SO(3):irrep_1]:3
```

**Comment by Gabri95** [comment]
Hi @pimdh 

Thanks for reporting this issue!

The Gimbal Lock warning is raised by [Rotation.as_euler()](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.as_euler.html) because certain 3D rotations allow for multiple *equivalent* Euler Angles parameterizations. 
This is not an issue since these parameterizations are all equivalent and are anyways only used to compute the Wigner D Matrices (which should be invariant to these re-parameterizations).

Anyways, I've now muted this warning, so it should not be printed anymore.

Thanks,
Gabriele
